application: videodiscoveries
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: backend.rest_api.app
  secure: always
- url: /blobstore/upload/
  script: backend.blob.app
  secure: always
  login: admin
- url: /blobstore/.*
  script: backend.blob.app
  secure: always
  login: required
- url: /static
  static_dir: frontend/static
  secure: always
  login: required
- url: /upload/
  script: frontend.web.app
  secure: always
  login: admin
- url: .*
  script: frontend.web.app
  secure: always
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: latest
- name: numpy
  version: latest

builtins:
- deferred: on